[phases.setup]
# Ensure Python 3 and pip are installed
runtime = "python3"

[phases.build]
# Install requirements
cmd = "pip install -r requirements.txt"

[phases.start]
# Start the Flask app
cmd = "python SearchEngine.py"