[phases.setup]
# Ensure Python 3 and pip are installed
runtime = "python3"

[phases.build]
# Install requirements
cmd = "pip3 install -r requirements.txt"

[phases.start]
# Start the Flask app
cmd = "python3 SearchEngine.py"